name: 'Generate PDF Action'
description: 'generate PDF of a webpage using ashuvssut/html2pdf-server upon every push in ashuvssut/ashuvssut-resume repo'
author: 'ashuvssut'
branding:
  icon: 'box'  
  color: 'green'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - run: node node_modules/puppeteer/install.js
      shell: bash
    - env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
      run: node src/action.js
      shell: bash
