name: 'Generate PDF Action'
description: 'generate PDF of a webpage using ashuvssut/html2pdf-server upon every push in ashuvssut/ashuvssut-resume repo'
author: 'ashuvssut'
branding:
  icon: 'box'  
  color: 'green'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install NPM dependencies
      run: npm install @actions/github puppeteer @vercel/ncc
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Creating Commit
      env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
      run: node dist/index.js
      shell: bash
